# Generated by Django 4.2.7 on 2023-12-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_listing_starting_bid_alter_category_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="starting_bid",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
