# Generated by Django 4.2.7 on 2023-12-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_remove_user_full_name_bid_bid_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
